#!/bin/sh
rm -rf Makefile Makefile.old MANIFEST* dbr_test.log t/sandbox/*/ blib pm_to_blib
git tag -f $1
perl -pi -e "s/-DBR-VERSION-TAG-/$1/" lib/DBR.pm Makefile.PL
perl ./Makefile.PL
make manifest
make dist
rm -rf Makefile Makefile.old MANIFEST* dbr_test.log t/sandbox/*/ blib pm_to_blib
git checkout lib/DBR.pm Makefile.PL
