#!/bin/zsh

echo "making install Makefile in $1 ..."

cd $1

echo "install: " > Makefile

for i in $(find . -type d -print); do
   az=${i//.\//}
   dni=`dirname $az`
   bni=`basename $az`

   echo -e '\tmkdir -p $(DESTDIR)/'$az >> Makefile
done

for i in $(find . -type f -print); do
   az=${i//.\//}
   dni=`dirname $az`
   bni=`basename $az`

   if [ "$bni" = "Makefile" ]; then
      continue;
   fi

   echo -e '\tinstall -c -m 0644 '$az' $(DESTDIR)/'$dni >> Makefile
done
